@base_url=http://localhost:5003/api

POST {{base_url}}/auth/signup
Content-Type: application/x-www-form-urlencoded

name=Rafael
&lastName=Mayer
&email=rafa.mayer67@gmail.com
&cpf=44480073833
&collegeName=PUC
&password=mayer123

###
POST {{base_url}}/auth/login
Content-Type: application/x-www-form-urlencoded

email=rafa.mayer67@gmail.com
&password=mayer123