services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - syncore
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - syncore

networks:
  syncore:
  
volumes:
  postgres-data: