services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5003:80'
    networks:
      - syncore
    environment:
      - 'ConnectionStrings__Postgres=User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=postgres;Pooling=true;'
