version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
