services:
  app:
    image: 'mayer2/syncore:latest'
    ports:
      - '13258:80'
    environment:
      - 'ConnectionStrings__Postgres=User ID=mayer;Password=rafamayer123;Host=10.124.0.2;Port=5432;Database=mayer;Pooling=true;'
    networks:
      - 'syncore'
    volumes:
      - 'syncore-DataProtection-Keys:/root/.aspnet/DataProtection-Keys'
    restart: unless-stopped

networks:
  syncore:

volumes:
  syncore-DataProtection-Keys:
