@base_url=http://localhost:5003/api

### GetAllPosts
GET {{base_url}}/posts
Cookie:.AspNetCore.Cookies=CfDJ8Kk4EOr7h9ZLmm1iroEXjqH6_DFOTknBpB1FK6UKnZfO9xpOr9FeULzSy8EMz_YeM9EmzrvC3di3MJ8dhBTnd2-iw3poz-rQFpGefKo-GX-ZoEtSaS_zxw9JFwnOZ4kU3goKqg7WRGeRbAPxSXQROcCNGU6Ptx0cr08QOmyVlMZXblp1ak-rECq9lso-0F6CoAUN7nzlszwXUMSZjjulWdIDTBUi-_7QZSXVRA8TOZLZ8e7cI6PaVFNootWyzewG32Ijip2qrnwFLIlttsN1kuER-XkH2g_nV0Ve4Zl0DSFojnVySkU6MWw94AUxAC-YDBL9EFSWnAHVjzBq5dGX41qXFtXGIkOn-JcBcFimQrz-ea-NV0hxlZQ0aZqovfPvbrzW5b6BQo5wKXJwP3c0u-6eIvueWvA65uMNHiGOTUsL4uMRTp8i4HMp2op9VryduQre-tZh1n1GDX3-KqMppko
