@base_url=http://localhost:5003/api

### SignUp
POST {{base_url}}/auth/sign-up
Content-Type: application/x-www-form-urlencoded

name=Rafael
&lastName=Mayer
&email=rafa.mayer67@gmail.com
&cpf=44480073833
&collegeName=PUC
&password=mayeeR09

### SignIn
POST {{base_url}}/auth/sign-in
Content-Type: application/x-www-form-urlencoded

email=rafa.mayer67@gmail.com
&password=mayeeR09

### Me
GET {{base_url}}/auth/me
Cookie: .AspNetCore.Cookies=CfDJ8Kk4EOr7h9ZLmm1iroEXjqH4pN_-Ck8H8ot1Q0000N_e2uUEkV4JPNGRjUoiukwR7EKdvVMjfmP3itpQmtXKQh_oD5DckK1l1kH89uBnU0EaNyiwtsmkFOKVPQynKy0rEdEMgnk5RnuygsGscSh98MC_FgLXGBDgChob1fyrgvrwnOp5bv_9YOPW2iAW6L70qCQASjJpOnf6kq06Q9uJxm6AaqQhOpmhiKt4Yk5a4WfNVFPB1kFzQfm4akFj4kxnblRRoW91Yk1GW1KgZ_qb59HhZ9KxUb58K8K73LNDSzDr4owPCNZbyw4GoV2Y832bh8Gqak7egaZWQ-yoDQkSuZ257QX-_gkkg7zFkVfF1BxuXX0a8nWMdfboieKro-Z27_ZuijVCPQBvbPXWUfaVo2Ee_iCcrtXJeZJDvVZldghVgghLi7RybJnh7SC-WazL3jfVucNKHV_ZdIuUPR_joAQ; path=/; samesite=lax; httponly

### CpfExists
GET {{base_url}}/auth/cpf-exists?cpf=44480073833

### EmailExists
GET {{base_url}}/auth/email-exists?email=rafa.mayer67@gmail.com

### EmailPasswordReset
POST {{base_url}}/auth/email-password-reset?email=rafa.mayer67@gmail.com

### PasswordReset
POST {{base_url}}/auth/password-reset
Content-Type: application/x-www-form-urlencoded

token=ACiJEw0y/kiGVlfycBdAVA==
&password=rafamayeR09
