@base_url=http://localhost:5003/api

### SignUp
POST {{base_url}}/auth/sign-up
Content-Type: application/x-www-form-urlencoded

name=Rafael
&lastName=Mayer
&email=rafa.mayer67@gmail.com
&cpf=44480073833
&collegeName=PUC
&password=mayeeR09

### SignIn
POST {{base_url}}/auth/sign-in
Content-Type: application/x-www-form-urlencoded

email=rafa.mayer67@gmail.com
&password=rafamayeR09

### Me
GET {{base_url}}/auth/me
Cookie: .AspNetCore.Cookies=CfDJ8Kk4EOr7h9ZLmm1iroEXjqE93XCn6edR5dlk8pYY-77_p2m8ttCNp-baHKVKOz5AMawFBCD7KTvQ9Qjg95TUvO2EQw67HpZ2hzRdqWcOTYR6AX4eTR0susKcncqTEbHJIcSL0acYvy2_SMHFLT5zRbPuhR4ceRVe_rmuJZ2UCA1a9kWhLa4JERLXqzmYlNrsijSH0erSVTtAcekgGJLFAHHYVY3OKEQp0bkeW_KGFHBaascjREaRGCFKHHDOJEvfwSXunn16GDWUlhhHyR_TOO_3pPLn7poI0rGVBY29XT50XsfroZ2RcVmWijxki-lgdK4aZATWea4HMYXjrrmIrHuqvUD0zcnmnN-I7uIZVyYVAOUcJTYEBViWsJsxCAeOnelKb-29E_shhKyMO9kf5myl-mJo8-ouuQAb20BSLgbvQoeTBJwCGeAW3Hyr08LVBzV54ClYjZBTGfcEg8xQKJ8; path=/; samesite=lax

### CpfExists
GET {{base_url}}/auth/cpf-exists?cpf=44480073833

### EmailExists
GET {{base_url}}/auth/email-exists?email=rafa.mayer67@gmail.com

### EmailPasswordReset
POST {{base_url}}/auth/email-password-reset?email=rafa.mayer67@gmail.com

### PasswordReset
POST {{base_url}}/auth/password-reset
Content-Type: application/x-www-form-urlencoded

token=ACiJEw0y/kiGVlfycBdAVA==
&password=rafamayeR09
