@base_url=http://localhost:5003/api
@cookie=.AspNetCore.Cookies=CfDJ8Bk1Q_cyBgRFqVjXa2GrmAKWZGiYasK6WWbks2xiBnJ4srbiHFxRPKXwQm1oWoq26vSeHduMwscKVI6RrIba9qjY4whIx0-hgJtNy6GJ0Oj7H88RmRGeeOOZ7RtOEy3h-djOYwf27u9eV8MZjRhrhcV21o8iluQbtz0DMhaBA9exWW5kZdV5LwT7HSVUhW1LgpdOVTcYiVbdhxa_GaNFn3pbc2iOMwTGIs0BVYFZuueodjv_GFYC2EJ0hUgkJFpP6zsPl-6JiwCz7yptLg7mw3JEuu7HE3jL222KPKceuBrqjDG1qx_UMi0mB9nYWB-ZBTTRiuxXJfDNUIGdIARgXBa9OO-OySyoapZr1QPM3pj4AL-IE2EHGCCmEoN2fHZRHzC6CLBouyGGNeVC_JZ5dlUwouNRSrbVKiKrThk6LjNyrxoYvpRod6R0AaI1oHRR-JUjSIehogCNLCB8iP5WQbM
@classId=1619eccc-f468-4e69-82b8-d27b88fbdc1c

### AddClass
POST {{base_url}}/classes
Content-Type: application/json
Cookie: {{cookie}}

{
  "Name": "Matéria 12",
  "Times": [
    {
      "DayOfWeek": 0,
      "StartHour": "21",
      "StartMinute": "05",
      "EndHour": "22",
      "EndMinute": "35"
    }
  ]
}

### GetAllClasses
GET {{base_url}}/classes
Cookie: {{cookie}}

### GetClassById
GET {{base_url}}/classes/{{classId}}
Cookie: {{cookie}}

### GetClassesSchedule
GET {{base_url}}/classes/schedule
Cookie: {{cookie}}

### DeactivateClass
POST {{base_url}}/classes/{{classId}}/deactivate
Cookie: {{cookie}}

### DeleteClass
DELETE {{base_url}}/classes/{{classId}}
Cookie: {{cookie}}