@base_url=http://localhost:5003/api
@cookie=.AspNetCore.Cookies=CfDJ8Kk4EOr7h9ZLmm1iroEXjqGf_N3fpEYnwNMNIO7307BYqRL7dtRKo5sAftlDDrO3F0QcO-GyoJpzAkL1JGf1qLP5nt-chyc6dIU4o-CcwZxM9FAQ8hJqoZlPr7_LKUaSPR1dT0C7n-TfhRiLooqR0ZcF5iZsZq9oBrzTLlr1EW56C4NyFXrB-e6okp3my4RgnsSX_RjhNB2exuqI_XM3B35MEK6m8mR3EdVcQtmMm7jMrrQOrFt5a4DZh4uuwgCIQUEBQAJUlkE4hxROKOzmF0bzWTxphQrh2aZIQzhFw4CCgwE2EK5XVSphb0cyKwXoVJCHFxWGhjjjaXW393757ayP1Lhngn_qTl44RPbRQe07rt8L3W0PRdhXHLO9TMaFeQw6FswHEr10_xOp10OXSQwhrFi0PeLC22WMgKcZVxdPnjCnmr6MaZiN3QZSzALY-2rLVrJtJyjahbG2M89sU4g
@classId=1619eccc-f468-4e69-82b8-d27b88fbdc1c

### AddClass
POST {{base_url}}/classes
Content-Type: application/json
Cookie: {{cookie}}

{
  "Name": "Matéria 7",
  "Times": [
    {
      "DayOfWeek": 0,
      "Hour": 19,
      "Minute": 20
    }
  ]
}

### GetAllClasses
GET {{base_url}}/classes
Cookie: {{cookie}}

### GetClassById
GET {{base_url}}/classes/{{classId}}
Cookie: {{cookie}}

### GetClassesSchedule
GET {{base_url}}/classes/schedule
Cookie: {{cookie}}

### DeactivateClass
POST {{base_url}}/classes/{{classId}}/deactivate
Cookie: {{cookie}}

### DeleteClass
DELETE {{base_url}}/classes/{{classId}}
Cookie: {{cookie}}