@base_url=http://localhost:5003/api
@cookie=.AspNetCore.Cookies=CfDJ8Bk1Q_cyBgRFqVjXa2GrmALDEPIFnJ2pZ1Mk_0kIKpQ02hnKhHFk3DN99MGKucaBQRXB0qYKt1zMXqYuFgT4RwtnEYLTe37Jr9VxEqL21fLG5UajGbDo0WIQf646fD2BaTTjXiPZoHydH39uPTyPhdv_9N5BTVJj0cZN2lgK8-rS4p1yUISefM7_FMqk6APPiy1jmj0WkbvOVUT2OWkhrY6WI1cNSVN9V45EOW6p-DFYvaUScFlE69BZWE8rJSTxi5_yWtz2hbUhQpUNztolChdppN-thRT-IPqOlixKNbn00wS2fOKGfNji8keSYGm9PuyrJyMeU-AKTGg5GH-4t8ipwUhytidEVKFlympdcDQ9qtMPDLYTJAmidpt27hvZGRpihgt8xGCuYIXViOgHS2HBJzwHXFlUZjOwDoA4Mr6h_pSwyDfFvVrCkGhXD44xgZ7BP6cXaXgHxHmnJeSr3ik; path=/; samesite=lax; httponly
@classId=cecde5d7-d8fd-4cb9-9434-2d6e5426ccf3

### AddClass
POST {{base_url}}/classes
Content-Type: application/json
Cookie: {{cookie}}

{
  "Name": "Matéria 2",
  "Times": [
    {
      "DayOfWeek": 0,
      "Hour": 19,
      "Minute": 20
    }
  ]
}

### GetAllClasses
GET {{base_url}}/classes
Cookie: {{cookie}}

### GetClassById
GET {{base_url}}/classes/{{classId}}
Cookie: {{cookie}}

### GetClassesSchedule
GET {{base_url}}/classes/schedule
Cookie: {{cookie}}

### DeactivateClass
POST {{base_url}}/classes/{{classId}}/deactivate
Cookie: {{cookie}}

### DeleteClass
DELETE {{base_url}}/classes/{{classId}}
Cookie: {{cookie}}